spring.application.name=telegram-bot
telegram.bot.token=7609619875:AAG21aLyRWpz9nn6Pg7zk_CRtDzXRUuppCU
telegram.bot.username=basicBasicInfo_bot
smartapi.base-url=http://localhost:8080
server.port=8081
logging.level.edu.lytvyniuk.telegrambot=DEBUG
logging.level.org.telegram=INFO