spring.application.name=telegram-bot
telegram.bot.token=7609619875:AAG21aLyRWpz9nn6Pg7zk_CRtDzXRUuppCU
telegram.bot.username=basicBasicInfo_bot
smartapi.base-url=http://localhost:8080
server.port=8081
logging.level.edu.lytvyniuk.telegrambot=DEBUG
logging.level.org.telegram=INFO

spring.datasource.url=jdbc:postgresql://localhost:5432/telegrambot
spring.datasource.username=postgres
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect